smart_bin/config/routes.rb
Rails.application.routes.draw do

  
  root 'static#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'braintree/payment' => "braintree#payment"
  get 'braintree/checkout' => "braintree#checkout"
  post 'braintree/checkout' => "braintree#checkout"

  get "/chart" => "users#chart"
  get "/chart/:id" => "users#chart"

  get "/area" => "users#area"
  get "/area/:id" => "users#area"
 

  post "/employee_profiles" => "users#employee_profiles"
  get "/employee_profiles" => "users#employee_profiles"

  get "/solutions", to: "static#solutions" 
  post "/solutions", to: "static#solutions" 

  get "/contact", to: "static#contact"
  post "/contact", to: "static#contact"

  get "/subscriptions/pricing_tables", to: "subscriptions#pricing_tables"
  post "/subscriptions/pricing_tables", to: "subscriptions#pricing_tables"

  get "/users", to: "users#index"
  get "/users/dashboard", to: "users#dashboard"
  get "/users/analytic", to: "users#analytic"
  get "/users/profile", to: "users#profile"
  
  get "/users/chart", to: "users#chart"

  devise_scope :user do
    post "/login" => "users/sessions#create"
    get "/login" => "users/sessions#create"
    post '/sign_in' => 'users/sessions#new'      
    get '/sign_in' => 'users/sessions#new'
    get '/devise/new' => 'users/sessions#new'  
    delete '/sign_out' => 'users/sessions#destroy'            
  end

  devise_for :users, controllers: { sessions: 'sessions' }

  resources :dustbins
  post "/dustbins/:id/update" => "dustbins#update"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

smart_bin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

smart_bin/app/models/area.rb
class Area < ApplicationRecord
    belongs_to :city
    belongs_to :state
    has_many :dustbins
end

smart_bin/app/models/city.rb
class City < ApplicationRecord
    belongs_to :state
    has_many :areas
    has_many :dustbins
end

smart_bin/app/models/company.rb
class Company < ApplicationRecord
    has_many :users
    has_many :groups
end

smart_bin/app/models/dustbin.rb
class Dustbin < ApplicationRecord
    #Geographical Info
    belongs_to :area
    belongs_to :city
    belongs_to :state
    belongs_to :fill_level
    #User to Dustbin Assignments
    has_many :user_dustbin_assignments
    has_many :users, through: :user_dustbin_assignments
    #User to Dustbin Assignments
    has_many :dustbin_stats
    #Raspberry Pi Connection

end

smart_bin/app/models/dustbin_stat.rb
class DustbinStat < ApplicationRecord
    belongs_to :dustbin
    def update
    end
end

smart_bin/app/models/fill_level.rb
class FillLevel < ApplicationRecord
    has_many :dustbins
end

smart_bin/app/models/group_dustbin_relations.rb
class Group_dustbin_relations < ApplicationRecord
end

smart_bin/app/models/raspberrypi.rb
class Raspberrypi < ApplicationRecord
    
end

smart_bin/app/models/state.rb
class State < ApplicationRecord
    has_many :cities
    has_many :areas
    has_many :dustbins
end

smart_bin/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_dustbin_assignments
  has_many :dustbins, through: :user_dustbin_assignments

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  enum role: ["admin", "company", "user"]
        
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

smart_bin/app/controllers/static_controller.rb
class StaticController < ApplicationController
end

smart_bin/app/controllers/users_controller.rb
class UsersController < ApplicationController
   # before_action :authenticate_user!
   respond_to :html, :js

   def area
    @area = Area.find(params[:id]) 
   end
   
   def chart
    # calculate bin stats here
    #assuming bin_id = 1   
    @mybin = Dustbin.find(params[:id]) 
    #fill level of individual bin per hour
    @dustbin_stat = @mybin.dustbin_stats
    @fill_level_percentage = [] 
    
    @dustbin_stat.each do |record|
      fill_level_id = record.fill_level_id
      @fill_level_percentage.push(FillLevel.find(fill_level_id).percentage.to_i)
    end

    #generate hourly timeline
    @hourly_timeline = []
    (1..24).each do |hour|      
      #IMPORTANT! WHEN YOU STORE STRING, TRAILING DOUBLE QUOTES WILL BE ATTACHED TO IT 
      #WHEN YOU PUSH TO ARRAY. THIS CAUSES AN ERROR IN THE CHART      
      @hourly_timeline.push(hour)
    end


    #how long does it take for a bin to fill up
    count = 0 
    @filled_up_time = []
    @dustbin_stat.each do |record|
      fill_level = record.fill_level_id      
      if fill_level == 1
        @filled_up_time.push(count)
        count = 0
      end
      count += 1
    end

    #generate timeline 
    @record_num = []
    (1..@filled_up_time.length).each do |number| 
      @record_num.push(number)
    end

    #fill rate per hour of an individual bin
    @fill_up_rate = [0]
    (1..@fill_level_percentage.length).each do |index|      

      if @fill_level_percentage[index].to_i == 0
        fill_rate = 0
        
      else
        fill_rate = @fill_level_percentage[index].to_i - @fill_level_percentage[index-1].to_i
        @fill_up_rate.push(fill_rate)      
      end

    end

    respond_to do |format|
      format.html
      format.js {render layout: false}
    end


  end


  def home

  end


  def create
  end 

  def index

    @geojson = Array.new

    if current_user.admin?
      @dustbins = Dustbin.all.order("fill_level_id DESC")
    elsif current_user.user?
      @dustbins = current_user.dustbins.order("fill_level_id DESC")
    end

    @dustbins.each do |d|
      #if d.fill_level_id > 7
        @geojson << {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [d.latitude.to_f, d.longitude.to_f]
          },
          properties: {
            code: d.name,
            address: d.address,
            level: d.fill_level.level,
            percentage: d.fill_level.percentage,
            color: d.fill_level.description,
          }
        }
      #end
    end

    respond_to do |format|
      format.html
      format.json { render json: @geojson }
    end

  end

  def dashboard
  end

  def analyic
  end

  def profile
  end

  def employe_profiles

  end


end

smart_bin/app/helpers/application_helper.rb
module ApplicationHelper

# calculate bin stats here
def individual_bin_level_per_hour(bin_id, num_of_hours)

   @dustbin_stat = DustbinStat.where('dustbin_id = "#{bin_id}"') 
   @fill_level_percentage = []    

   @dustbin_stat.each do |record|
      fill_level_id = record.fill_level_id
      @fill_level_percentage.push(FillLevel.find(fill_level_id).percentage.to_i)
   end   

    #generate hourly timeline
    @hourly_timeline = []
    (1..num_of_hours).each do |hour|      
      #IMPORTANT! WHEN YOU STORE STRING, TRAILING DOUBLE QUOTES WILL BE ATTACHED TO IT 
      #WHEN YOU PUSH TO ARRAY. THIS CAUSES AN ERROR IN THE CHART      
      @hourly_timeline.push(hour)
   end   
end

def time_to_fill_up_bin(bin_id)
   #how long does it take for a bin to fill up
   @dustbin_stat = DustbinStat.where('dustbin_id = "#{bin_id}"') 
   count = 0 
   @filled_up_time = []
   @dustbin_stat.each do |record|
      fill_level = record.fill_level_id      
      if fill_level == 1
       @filled_up_time.push(count)
       count = 0
    end
    count += 1
 end

    #generate timeline 
    @record_num = []
    (1..@filled_up_time.length).each do |number| 
      @record_num.push(number)
   end
end





end

smart_bin/app/helpers/braintree_helper.rb
module BraintreeHelper
end

smart_bin/app/helpers/dustbin_helper.rb
module DustbinHelper
end

smart_bin/app/helpers/login_helper.rb
module LoginHelper
end

smart_bin/app/helpers/static_helper.rb
module StaticHelper
end

smart_bin/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

smart_bin/app/helpers/users_helper.rb
module UsersHelper
end

smart_bin/app/views/layouts/_flash_devise.html.erb
<% if notice != nil %>
  <div class="alert alert-success" role="alert">
    <button class="close" data-dismiss="alert">×</button>
    <%= notice %>
  </div>
<% end %>

<% if alert != nil  %>
  <div class="alert alert-danger" role="alert">
    <button class="close" data-dismiss="alert">×</button>
    <%= alert %>
  </div>
<% end %>

smart_bin/app/views/layouts/_footer.html.erb
<tr>
<footer>
    <p class="text-center">Copyright &#169; 2018, Binberries</p></div>
</footer>

smart_bin/app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-expand-lg 
        <% if controller_name == "static" %>
          fixed-top 
        <% end %>
        <% if controller_name != "static" %>
          navbar-shrink
        <% end %>" id="mainNav">
      <div class="container">
        <i class="far fa-trash-alt-2x"></i> <%= link_to "Binberries", root_path, class: "navbar-brand js-scroll-trigger" %>   
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            <% if !user_signed_in? %>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="#solutions">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="#subscriptions">Subscriptions</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
                </li>
                <li class="nav-item">
                  <%= link_to "Client Login", "/sign_in", class: "nav-link"%> 
                </li>
            <% else %>
                <li class="nav-item">         
                  <%= link_to "Dashboard", users_path, class: "nav-link"%>
                </li>
                <% if current_user.admin? %>
                <li class="nav-item">
                  <%= link_to "Admin", rails_admin_path, class: "nav-link" %>
                </li>
                <% end %>
                <li class="nav-item">
                  <%= link_to "Sign Out", "/sign_out", method: :delete, class: "nav-link"%>   
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

smart_bin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Binberries Smart City</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'favicon_raspberry.png' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Load the Client component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
    <!-- Load the Hosted Fields component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    
  </head>

  <body id="page-top">
    <% if user_signed_in? %>
      <%= render partial: "users/navbar" %>
    <% else %>
      <%= render partial: "static/navbar" %>
    <% end %>

    <%= yield %>

    <%# <%= render template: "static/modal" %>

  </body>

  <%= render partial: "layouts/footer" %>

</html>

smart_bin/app/views/reportings/area.html.erb
<% @dustbins.area.each do |d| %>
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="background:whitesmoke;"><br>
                <h3>Area Summary</h3>
                <div class="row">
                    <div class="col-md-6">
                        <%= column_chart d.dustbins.group(:id).limit(10).pluck("dustbins.code, sum((dustbins.fill_level_id-1)*10) as fill_level"),
                        title: "Latest Top Ten Highest Fill Level (%)",
                        colors: ['pink'],
                        library: {
                            tooltip: {
                            pointFormat: 'Times Bought: <b>{point.y}</b>'
                            }
                        } %>
                    </div>

                    <div class="col-md-6">
                        <%= line_chart d.dustbins.group(:id).limit(10).pluck("dustbins.code, sum((dustbins.fill_level_id-1)*10) as fill_level"),
                        title: "Latest Top Ten Highest Fill Level (%)",
                        colors: ['aquamarine'],
                        library: {
                            tooltip: {
                            pointFormat: 'Times Bought: <b>{point.y}</b>'
                            }
                        } %>
                    </div>

                    <div class="col-md-12">
                        <%= line_chart d.dustbins.limit(5).map { |d|
                            {name: d.code, data: d.dustbin_stats.group_by_hour(:collected_at, format: "%b %d %l %P", last: 24).sum(:fill_level_id)}
                        },
                        title: "Top 5 Dustbins Last 24h Daily Trending",
                        library: {
                            tooltip: {
                            pointFormat: 'Times Bought: <b>{point.y}</b>'
                            }
                        }
                        %>
                    </div>
                </div>
            </div>

        </div>
    </div>

smart_bin/app/views/reportings/dustbin.html.erb
<div class="container">

    <div class="row">
        <div class="col-md-4">
            <p>Trash Bin Capacity: 200ℓ</p>
            <p>Fill Up per Day: 50ℓ</p>
            <p>Average Day to Collect: 4days</p>
        </div>
        <div class="col-md-4">
            Average Litres/Day:
        </div>
        <div class="col-md-4">
            Average Litres/Day:
        </div>    
    </div>

    <div class="row">
        <div class="col-md-12" style="background:whitesmoke;"><br>
            <h3>Account Summary</h3>
            <div class="row">
                <div class="col-md-6">
                    <%= column_chart @dustbins.group(:id).limit(10).pluck("dustbins.code, sum((dustbins.fill_level_id-1)*10) as fill_level"),
                    title: "Latest Top Ten Highest Fill Level (%)",
                    colors: ['pink'],
                    library: {
                        tooltip: {
                        pointFormat: 'Times Bought: <b>{point.y}</b>'
                        }
                    } %>
                </div>

                <div class="col-md-6">
                    <%= line_chart @dustbins.group(:id).limit(10).pluck("dustbins.code, sum((dustbins.fill_level_id-1)*10) as fill_level"),
                    title: "Latest Top Ten Highest Fill Level (%)",
                    colors: ['aquamarine'],
                    library: {
                        tooltip: {
                        pointFormat: 'Times Bought: <b>{point.y}</b>'
                        }
                    } %>
                </div>

                <div class="col-md-12">
                    <%= line_chart @dustbins.limit(5).map { |d|
                        {name: d.code, data: d.dustbin_stats.group_by_hour(:collected_at, format: "%b %d %l %P", last: 24).sum(:fill_level_id)}
                    },
                    title: "Top 5 Dustbins Last 24h Daily Trending",
                    library: {
                        tooltip: {
                        pointFormat: 'Times Bought: <b>{point.y}</b>'
                        }
                    }
                    %>
                </div>
            </div>
        </div>

    </div>
</div>