smart_bin/config/routes.rb
Rails.application.routes.draw do

  
  root 'static#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'braintree/payment' => "braintree#payment"
  get 'braintree/checkout' => "braintree#checkout"
  post 'braintree/checkout' => "braintree#checkout"

  get "/chart" => "users#chart"
  get "/chart/:id" => "users#chart"

  get "/area" => "users#area"
  get "/area/:id" => "users#area"
 

  post "/employee_profiles" => "users#employee_profiles"
  get "/employee_profiles" => "users#employee_profiles"

  get "/solutions", to: "static#solutions" 
  post "/solutions", to: "static#solutions" 

  get "/contact", to: "static#contact"
  post "/contact", to: "static#contact"

  get "/subscriptions/pricing_tables", to: "subscriptions#pricing_tables"
  post "/subscriptions/pricing_tables", to: "subscriptions#pricing_tables"

  get "/users", to: "users#index"
  get "/users/dashboard", to: "users#dashboard"
  get "/users/analytic", to: "users#analytic"
  get "/users/profile", to: "users#profile"
  
  get "/users/chart", to: "users#chart"

  devise_scope :user do
    post "/login" => "users/sessions#create"
    get "/login" => "users/sessions#create"
    post '/sign_in' => 'users/sessions#new'      
    get '/sign_in' => 'users/sessions#new'
    get '/devise/new' => 'users/sessions#new'  
    delete '/sign_out' => 'users/sessions#destroy'            
  end

  devise_for :users, controllers: { sessions: 'sessions' }

  resources :dustbins
  post "/dustbins/:id/update" => "dustbins#update"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

smart_bin/app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  respond_to :html, :js

 def payment        
    #only make this page accessable to the current user
    if false
      redirect_to root_url
    else
      @client_token = Braintree::ClientToken.generate        
    end

  end

  def checkout    

   payable_amount = 10

   nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

   result = Braintree::Transaction.sale(
    :amount => payable_amount, 
    :payment_method_nonce => nonce_from_the_client,
    :options => {
     :submit_for_settlement => true
   }
   )

   if result.success?   
    redirect_to root_url
  else
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end

end
end

smart_bin/app/helpers/braintree_helper.rb
module BraintreeHelper
end

smart_bin/app/views/braintree/_payment.html.erb
<%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>
  <div class="payment-frame">

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>

  </div>
<%end%>

<%= javascript_include_tag "braintree" %>






    

smart_bin/app/views/braintree/payment.js.erb
$("#modal-window").find(".modal-body").html("<%= j (render 'payment') %>");
$("#modal-window").find(".modal-title").html("Subscribe");
//If need this button to be able to submit a form id ("form", "(element_id)")
//$("#submit-form").attr("form", "new_user");
$("#submit-form").html("Submit");
$("#submit-form").hide();
//$("#submit-form").show();
$("#modal-window").modal();