smart_bin/config/routes.rb
Rails.application.routes.draw do

  
  root 'static#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'braintree/payment' => "braintree#payment"
  get 'braintree/checkout' => "braintree#checkout"
  post 'braintree/checkout' => "braintree#checkout"

  get "/chart" => "users#chart"
  get "/chart/:id" => "users#chart"

  get "/area" => "users#area"
  get "/area/:id" => "users#area"
 

  post "/employee_profiles" => "users#employee_profiles"
  get "/employee_profiles" => "users#employee_profiles"

  get "/solutions", to: "static#solutions" 
  post "/solutions", to: "static#solutions" 

  get "/contact", to: "static#contact"
  post "/contact", to: "static#contact"

  get "/subscriptions/pricing_tables", to: "subscriptions#pricing_tables"
  post "/subscriptions/pricing_tables", to: "subscriptions#pricing_tables"

  get "/users", to: "users#index"
  get "/users/dashboard", to: "users#dashboard"
  get "/users/analytic", to: "users#analytic"
  get "/users/profile", to: "users#profile"
  
  get "/users/chart", to: "users#chart"

  devise_scope :user do
    post "/login" => "users/sessions#create"
    get "/login" => "users/sessions#create"
    post '/sign_in' => 'users/sessions#new'      
    get '/sign_in' => 'users/sessions#new'
    get '/devise/new' => 'users/sessions#new'  
    delete '/sign_out' => 'users/sessions#destroy'            
  end

  devise_for :users, controllers: { sessions: 'sessions' }

  resources :dustbins
  post "/dustbins/:id/update" => "dustbins#update"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

smart_bin/app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

   def pricing_tables
   end



end

smart_bin/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

smart_bin/app/views/subscriptions/pricing_tables.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Subscription Plans                
            </h1>
            <ol class="breadcrumb">
                <li><%= link_to 'Home', root_path %>
                </li>
                <li class="active">Pricing Table</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <h3 class="panel-title">Basic</h3>
                </div>
                <div class="panel-body">
                    <span class="price"><sup>$</sup>19<sup>99</sup></span>
                    <span class="period">per month</span>
                </div>
                <ul class="list-group">
                    <li class="list-group-item"><strong>1</strong> User</li>
                    <li class="list-group-item"><strong>5</strong> Projects</li>
                    <li class="list-group-item"><strong>Unlimited</strong> Email Accounts</li>
                    <li class="list-group-item"><strong>10GB</strong> Disk Space</li>
                    <li class="list-group-item"><strong>100GB</strong> Monthly Bandwidth</li>
                    <li class="list-group-item"><%= link_to 'Subscribe', braintree_payment_path, :class => 'btn btn-primary' %>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-primary text-center">
                <div class="panel-heading">
                    <h3 class="panel-title">Plus <span class="label label-success">Best Value</span></h3>
                </div>
                <div class="panel-body">
                    <span class="price"><sup>$</sup>39<sup>99</sup></span>
                    <span class="period">per month</span>
                </div>
                <ul class="list-group">
                    <li class="list-group-item"><strong>10</strong> User</li>
                    <li class="list-group-item"><strong>500</strong> Projects</li>
                    <li class="list-group-item"><strong>Unlimited</strong> Email Accounts</li>
                    <li class="list-group-item"><strong>1000GB</strong> Disk Space</li>
                    <li class="list-group-item"><strong>10000GB</strong> Monthly Bandwidth</li>
                    <li class="list-group-item"><%= link_to 'Subscribe', braintree_payment_path, :class => 'btn btn-primary' %>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <h3 class="panel-title">Ultra</h3>
                </div>
                <div class="panel-body">
                    <span class="price"><sup>$</sup>159<sup>99</sup></span>
                    <span class="period">per month</span>
                </div>
                <ul class="list-group">
                    <li class="list-group-item"><strong>Unlimted</strong> Users</li>
                    <li class="list-group-item"><strong>Unlimited</strong> Projects</li>
                    <li class="list-group-item"><strong>Unlimited</strong> Email Accounts</li>
                    <li class="list-group-item"><strong>10000GB</strong> Disk Space</li>
                    <li class="list-group-item"><strong>Unlimited</strong> Monthly Bandwidth</li>
                    <li class="list-group-item"><%= link_to 'Subscribe', braintree_payment_path, :class => 'btn btn-primary' %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->